/*
 * OpenJMLUnit
 * 
 * @author "Daniel M. Zimmerman (dmz@acm.org)"
 * @module "OpenJML"
 * @creation_date "March 2010"
 * @last_updated_date "March 2010"
 * @keywords "unit testing", "JML"
 */

package org.jmlspecs.openjmlunit.iterator;

/**
 * A repeated access iterator that generates arrays of objects by reflectively
 * using iterator generation methods to refresh individual array element iterators.
 *  
 * @author Daniel M. Zimmerman
 * @version March 2010
 */
public class ObjectArrayIterator implements RepeatedAccessIterator {
  // Constraints
  
  // @constraint "The sequence of elements returned consists of arrays of objects,
  //              where each object is generated by using an iterator provided by
  //              the iterator generation method in the corresponding position of
  //              the list."
}
