
package org.jmlspecs.jmlunitng.strategies;

/**
 * This class creates a basic strategy for generating an iterator.
 * 
 * @author Rinkesh Nagmoti.
 * @version 1.0
 */
public abstract class AbstractBasicStrategy
{
  /**
   * This is the iterator generated by the strategy.
   */
  protected final transient StrategyIterator my_itr;

  /**
   * This is the constructor.
   */
  public AbstractBasicStrategy()
  {
    my_itr = new MultiIterator(addData(), addDataForAll(), defaultData());
  }

  /**
   * This method returns the created iterator.
   * 
   * @return ParameterIterator
   */
  public StrategyIterator iterator()
  {
    return my_itr;
  }

  /**
   * This method return the default data for iterator.
   * 
   * @return Object[]
   */
  public abstract StrategyIterator defaultData();

  /**
   * This method return the user provided data for iterator.
   * 
   * @return Object[]
   */
  public abstract StrategyIterator addData();

  /**
   * This method return the user provided data for all iterators of one kind.
   * 
   * @return Object[]
   */
  public abstract StrategyIterator addDataForAll();

}
