
package org.jmlspecs.jmlunitng;

/**
 * An interface for defining constants.
 * 
 * @author Rinkesh Nagmoti
 * @version 1.0 Some of the code is borrowed from open source JMLUNIT interface
 *          org.jmlspecs.jmlunit.Constants
 */
public interface Constants 
{

  /** Post fix for the Test Class generated by JMLUnitNG. */
  String T_C_POSTFIX = "_JMLUNITNG_Test";
  /** Post fix for the file name of the Test Class generated by JMLUnitNG. */
  String T_C_FILE_POSTFIX = "_JMLUNITNG_Test.java";
  /** Post fix for the TestData Class generated by JMLUnitNG. */
  String TEST_DATA_POSTFIX = "_JMLUNITNG_Test_Data";
  /**
   * Post fix for the file name of the TestData Class generated by JMLUnitNG.
   */
  String T_D_FILE_POSTFIX = "_JMLUNITNG_Test_Data.java";
  /** A Dot Java extension for the file names. */
  String DOT_JAVA = ".java";

  /** The name of the JUnit framework package. */
  String PKG_JUNIT = "junit.framework.";
  /** The name of the JML RAC runtime package. */
  String PKG_JMLRAC = "org.jmlspecs.jmlrac.runtime.";
  /** The name of the JML jmlunitng package. */
  String PKG_JMLUNITNG = "org.jmlspecs.jmlunitng.";
  /** The name of the JML jmlunitng strategies package. */
  String PKG_STRATEGIES = "org.jmlspecs.jmlunitng.strategies.";
  /** This is the start of javadoc.*/
  String JDOC_ST = "/**";
  /** This is the end of javadoc.*/
  String JDOC_END = " */";
  /** This is the Parameter start.*/
  String PARAM_ST = "the_";
  /**This is the bracket start.*/
  String BKT_ST = "(";
  /**This is the bracket end.*/
  String BKT_END = ")";
  /**This is the block start.*/
  String BLK_ST = "{";
  /**This is the block end.*/
  String BLK_END = "}";
  /**This is the square bracket start.*/
  String SQ_BCK_ST = "[";
  /**This is the square bracket end.*/
  String SQ_BCK_END = "]";
  /**This is the semicolon sign.*/
  String SM_COLN = ";";
  /**This is the get method string.*/
  String GET = ".get();"; 
  /**This is the advance method string.*/
  String ADV = ".advance();"; 
  /**This is the brackets string.*/
  String BKTS = "()"; 
  /**This is the period string.*/
  String PERIOD = ".";
  /**This is the "String" string.*/
  String STR = "String";
  /**This is the "String[]" string.*/
  String STRARR = "String[]";
  /**This is the "=" string.*/
  String EQUAL = " = ";
  /**
   * This is the underscore sign.
   */
  String UND = "_";
  /**
   * This is the constants for indentation.
   */
  int ONE = 1;
  /**
   * This is the constants for indentation.
   */
  int LEVEL1 = 2;
  /**
   * This is the constants for indentation.
   */
  int LEVEL2 = 4;
  /**
   * This is the constants for indentation.
   */
  int LEVEL3 = 6;
  /**
   * This is the constants for indentation.
   */
  int LEVEL4 = 8;
  /**
   * This is the constants for indentation.
   */
  int LEVEL5 = 10;

  /*
   * @ invariant PKG_JUNIT.length() > 0
   * 
   * @ ==> PKG_JUNIT.charAt(PKG_JUNIT.length()) == '.';
   * 
   * @
   */
  /*
   * @ invariant PKG_JMLRAC.length() > 0
   * 
   * @ ==> PKG_JMLRAC.charAt(PKG_JMLRAC.length()) == '.';
   * 
   * @
   */
  /*
   * @ invariant PKG_JMLUNITNG.length() > 0
   * 
   * @ ==> PKG_JMLUNITNG.charAt(PKG_JMLUNITNG.length()) == '.';
   * 
   * @
   */
  /*
   * @ invariant PKG_STRATEGIES.length() > 0
   * 
   * @ ==> PKG_STRATEGIES.charAt(PKG_JMLUNITNG.length()) == '.';
   * 
   * @
   */
}
