package org.jmlspecs.jmlunitng;

import java.io.FileNotFoundException;
import java.util.Date;

import org.multijava.mjc.JTypeDeclarationType;



/**
 * Generates the JMLUNITNG_Test class by JMLUNITNG framework.
 * The generated class runs unit tests for the class to be
 * tested using JMLUNITNG testing framework.
 * @author Rinkesh Nagmoti
 * @version 1.0
 */
public class JMLUNITNGTestClassGenerator implements Constants{

/** Constructs the JMLUNITNGTestClassGenerator Object.*/
	public JMLUNITNGTestClassGenerator(String file) {
		this.file = file;
		try {
			writer = new Writer(file);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
	
/** Calls other methods to generate the Test Class.*/
	public void createTest(){
	/*
	 * Generate the test here.
	 */

	}

/** Prints Class header import statements and class Javadoc comment.*/	
	private void printHeaderImportandJavadoc(JTypeDeclarationType decl) {
		
		
		writer.print("This class is generated by JMLUNITNG on"+new Date());
		writer.newLine(2);
		writer.print("/** This class is the test oracle generated by JMLUNITNG testing framework");
		writer.print(" *  for class");
	}
	
	public static void main(String[] args){
		JMLUNITNGTestClassGenerator j = new JMLUNITNGTestClassGenerator("C:\\rinkesh.java");
		j.createTest();
	}
	//-----------------
	// DATA MEMBERS
	//-----------------
	/** Writer class object to print the Test Class.*/
	private Writer writer;

	/** String representing the file name and location for Test Class*/
	private String file;
	
	/** JTypeDeclarationType object which holds information about the class 
	 * for which the test is to be conducted.
	 */
	private JTypeDeclarationType declarationType;
}
